In [2]:
from sklearn import datasets
iris = datasets.load_iris()
X, y = iris.data, iris.target

In [6]:
from pybrain.datasets.classification import ClassificationDataSet

dataset = ClassificationDataSet(4, 1, nb_classes=3)

for i in range(len(X)):
    dataset.addSample(X[i], y[i])
    
dataset['input']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
dataset['target']

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [8]:
dataset

In [9]:
train_data, part_data = dataset.splitWithProportion(0.6)

In [10]:
len(train_data)

90

In [11]:
len(part_data)

60

In [12]:
test_data, val_data = part_data.splitWithProportion(0.5)
len(test_data)

30

In [13]:
from pybrain.tools.shortcuts import buildNetwork
from pybrain.supervised.trainers import BackpropTrainer

In [14]:
dataset.outdim

1

In [15]:
dataset.indim

4

In [16]:
net = buildNetwork(dataset.indim, 3, dataset.outdim)
trainer = BackpropTrainer(net, dataset=train_data, learningrate=0.01, momentum=0.1, verbose=True)
train_erros, val_erros = trainer.trainUntilConvergence(dataset=train_data, maxEpochs=100)

Total error:  0.718970226324
Total error:  0.380512792901
Total error:  0.353577433919
Total error:  0.344126171644
Total error:  0.340663553119
Total error:  0.340438361029
Total error:  0.339270388262
Total error:  0.338422765554
Total error:  0.337450414503
Total error:  0.336857587355
Total error:  0.337205288769
Total error:  0.336396706453
Total error:  0.335344987011
Total error:  0.332823254138
Total error:  0.334067807007
Total error:  0.335606858559
Total error:  0.335249166508
Total error:  0.335432552359
Total error:  0.335068365229
Total error:  0.33468977213
Total error:  0.3350716998
Total error:  0.33485805549
Total error:  0.334615800442
Total error:  0.33214068799
Total error:  0.335340284163
Total error:  0.334417250301
Total error:  0.334628565919
Total error:  0.334247774175
Total error:  0.334469658029
Total error:  0.334746955496
Total error:  0.328717341852
Total error:  0.334856579012
Total error:  0.334240882714
Total error:  0.334049164332
Total error:  0.334

In [17]:
import matplotlib.pyplot as plt

plt.plot(train_erros, 'b', val_erros, 'r')

trainer.totalepochs

101

In [18]:
trainer.trainOnDataset(train_data, 500)

Total error:  0.328645123689
Total error:  0.328855081662
Total error:  0.327778542227
Total error:  0.325458369031
Total error:  0.330744250151
Total error:  0.3290049527
Total error:  0.327322671182
Total error:  0.327671661157
Total error:  0.328716277962
Total error:  0.328481730543
Total error:  0.328213725667
Total error:  0.328800204762
Total error:  0.327388664819
Total error:  0.328823975394
Total error:  0.328767983082
Total error:  0.325925806599
Total error:  0.32894207393
Total error:  0.328430244916
Total error:  0.328058769759
Total error:  0.328703896519
Total error:  0.328585908707
Total error:  0.32469840582
Total error:  0.329014017067
Total error:  0.328890906521
Total error:  0.328411330662
Total error:  0.326068281666
Total error:  0.326954352175
Total error:  0.325545387239
Total error:  0.329324942092
Total error:  0.326829026628
Total error:  0.329091035689
Total error:  0.329093473338
Total error:  0.326788114755
Total error:  0.329053847043
Total error:  0.32

Total error:  0.0235709583746
Total error:  0.0220818874218
Total error:  0.0213297975592
Total error:  0.0231973638699
Total error:  0.0226148769412
Total error:  0.022800240671
Total error:  0.0240852468962
Total error:  0.0231465044237
Total error:  0.0231632970162
Total error:  0.0222815473815
Total error:  0.0235156984376
Total error:  0.0221891250074
Total error:  0.0228074019581
Total error:  0.0232182420673
Total error:  0.0219823099572
Total error:  0.0222478687165
Total error:  0.0222247406441
Total error:  0.0223673782783
Total error:  0.0218818017016
Total error:  0.0238990044373
Total error:  0.0235565745132
Total error:  0.0188727106111
Total error:  0.0238910563769
Total error:  0.0235586353797
Total error:  0.0230660383697
Total error:  0.0234155636647
Total error:  0.0217384269137
Total error:  0.0222796504377
Total error:  0.0229020638003
Total error:  0.0226807010084
Total error:  0.0222023777363
Total error:  0.0218243235983
Total error:  0.0233521074264
Total error

In [19]:
out = net.activateOnDataset(test_data)
for i in range(len(out)):
    print('out: %f, correct: %f' % (out[i], test_data['target'][i]))

out: 1.945253, correct: 2.000000
out: 0.026945, correct: 0.000000
out: 2.050549, correct: 2.000000
out: -0.004033, correct: 0.000000
out: 1.992665, correct: 2.000000
out: 1.670573, correct: 2.000000
out: 1.040882, correct: 1.000000
out: 1.719260, correct: 2.000000
out: 0.004343, correct: 0.000000
out: 2.034745, correct: 2.000000
out: 1.917940, correct: 2.000000
out: 0.124911, correct: 0.000000
out: 0.036980, correct: 0.000000
out: 1.029938, correct: 1.000000
out: -0.019212, correct: 0.000000
out: 0.036129, correct: 0.000000
out: 1.402451, correct: 1.000000
out: 1.910564, correct: 2.000000
out: 2.033519, correct: 2.000000
out: 1.019898, correct: 1.000000
out: 1.820817, correct: 2.000000
out: 0.054404, correct: 0.000000
out: 0.011792, correct: 0.000000
out: 1.779514, correct: 2.000000
out: 1.196963, correct: 1.000000
out: 0.001804, correct: 0.000000
out: 1.036021, correct: 1.000000
out: 1.585239, correct: 2.000000
out: 1.742420, correct: 2.000000
out: 2.070954, correct: 2.000000


In [20]:
print(type(dataset))
print(type(train_data))

<class 'pybrain.datasets.classification.ClassificationDataSet'>
<class 'pybrain.datasets.supervised.SupervisedDataSet'>


In [21]:
from sklearn import datasets
from pybrain.datasets.classification import ClassificationDataSet
from pybrain.tools.shortcuts import buildNetwork
from pybrain.supervised.trainers import BackpropTrainer

In [29]:
iris = datasets.load_iris()
X, y = iris.data, iris.target
dataset = ClassificationDataSet(4, 1, nb_classes=3)

for i in range(len(X)):
    dataset.addSample(X[i], y[i])

train_data_temp, part_data_temp = dataset.splitWithProportion(0.6)
test_data_temp, val_data_temp = part_data_temp.splitWithProportion(0.5)    

type(train_data_temp)

pybrain.datasets.supervised.SupervisedDataSet

In [41]:
train_data = ClassificationDataSet(4, 1, nb_classes=3)
for n in range(train_data_temp.getLength()):
    train_data.addSample(train_data_temp.getSample(n)[0], train_data_temp.getSample(n)[1])

test_data = ClassificationDataSet(4, 1, nb_classes=3)
for n in range(test_data_temp.getLength()):
    test_data.addSample(test_data_temp.getSample(n)[0], test_data_temp.getSample(n)[1])

val_data = ClassificationDataSet(4, 1, nb_classes=3)
for n in range(val_data_temp.getLength()):
    val_data.addSample(val_data_temp.getSample(n)[0], val_data_temp.getSample(n)[1])

print('Antes do _convertToOneOfMany')
print(train_data['target'][:5])

train_data._convertToOneOfMany()
test_data._convertToOneOfMany()
val_data._convertToOneOfMany()

print('Depois do _convertToOneOfMany')
print(train_data['target'][:5])

print('---------')

from pybrain.structure.modules import SoftmaxLayer

net = buildNetwork(4, 5, 3, outclass=SoftmaxLayer)
trainer = BackpropTrainer(net, dataset = train_data, learningrate=0.01, momentum=0.5)
trainer.trainOnDataset(train_data, 500)

from pybrain.utilities import percentError

out = net.activateOnDataset(test_data).argmax(axis=1)
print('Erro teste: %f%%' % percentError(out, test_data['class']))

print('--------------')

import numpy

out = net.activateOnDataset(val_data).argmax(axis=1)
print('Erro validação: %f%%' % percentError(out, val_data['class']))

print('saida: \t', out)
print('correto:\t', val_data['class'][:,0])

Antes do _convertToOneOfMany
[[2]
 [1]
 [2]
 [1]
 [2]]
Depois do _convertToOneOfMany
[[0 0 1]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]]
---------
Erro teste: 6.666667%
--------------
Erro validação: 3.333333%
saida: 	 [0 1 0 0 2 0 1 1 0 1 2 1 0 1 1 1 2 2 1 2 2 2 0 2 2 2 2 0 1 1]
correto:	 [0 1 0 0 2 0 1 1 0 1 2 2 0 1 1 1 2 2 1 2 2 2 0 2 2 2 2 0 1 1]
