In [4]:
import numpy as np

In [5]:
# x entradas e y saidas
x = np.genfromtxt('balance-scale.data',delimiter=',',usecols=(1,2,3,4))
y = np.genfromtxt('balance-scale.data',delimiter=',',usecols=(0))
print(x)
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 2.]
 [1. 1. 1. 3.]
 ...
 [5. 5. 5. 3.]
 [5. 5. 5. 4.]
 [5. 5. 5. 5.]]
[2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 1. 2. 3. 3. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 1. 1. 2. 3. 3. 1. 3. 3. 3. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 1. 1. 1. 2. 3. 1. 2. 3. 3. 3. 1. 3. 3. 3. 3. 2. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 1. 1. 1. 1. 2. 1. 1. 3. 3. 3. 1. 3. 3. 3. 3. 1. 3. 3. 3. 3.
 2. 3. 3. 3. 3. 1. 2. 3. 3. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 1. 1. 1. 2. 3. 1. 2. 3. 3. 3. 1. 3. 3. 3. 3. 2. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 1. 1. 1. 1. 1. 1. 1. 2. 3. 3. 1. 2. 3. 3. 3. 1. 3.
 3. 3. 3. 1. 3. 3. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 3. 3. 3. 1.
 2. 3. 3. 3. 1. 3. 3. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 3.
 1. 1. 3. 3. 3. 1. 2. 3. 3. 3. 1. 1. 2. 3. 3. 1. 3. 3. 3. 3. 2. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 1. 1. 1. 1. 1. 1. 1. 2. 3. 3. 1. 2. 3.
 3. 3. 1. 3. 3. 3. 3. 1. 3. 

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state=42)
x_treino

array([[2., 4., 1., 5.],
       [1., 4., 3., 4.],
       [5., 1., 5., 3.],
       ...,
       [3., 1., 5., 1.],
       [4., 3., 3., 1.],
       [1., 5., 1., 3.]])

In [8]:
x_teste

array([[4., 3., 5., 3.],
       [4., 5., 3., 1.],
       [2., 4., 4., 1.],
       [2., 4., 3., 3.],
       [4., 5., 2., 1.],
       [5., 1., 4., 1.],
       [2., 2., 3., 4.],
       [1., 4., 1., 3.],
       [5., 2., 1., 3.],
       [2., 1., 5., 1.],
       [3., 1., 4., 1.],
       [1., 2., 2., 2.],
       [1., 3., 2., 1.],
       [1., 4., 4., 1.],
       [5., 3., 2., 3.],
       [1., 4., 1., 2.],
       [1., 1., 1., 3.],
       [3., 5., 4., 4.],
       [4., 1., 5., 1.],
       [3., 2., 3., 2.],
       [2., 1., 2., 2.],
       [2., 1., 5., 4.],
       [1., 2., 5., 5.],
       [5., 5., 5., 2.],
       [4., 3., 3., 3.],
       [1., 5., 3., 1.],
       [3., 1., 2., 3.],
       [5., 4., 1., 4.],
       [5., 5., 5., 1.],
       [3., 1., 2., 2.],
       [3., 4., 2., 5.],
       [3., 1., 3., 2.],
       [2., 3., 2., 5.],
       [5., 3., 1., 5.],
       [2., 1., 2., 3.],
       [4., 5., 3., 3.],
       [3., 4., 3., 1.],
       [5., 5., 3., 3.],
       [2., 3., 2., 2.],
       [5., 4., 5., 5.],


In [9]:
y_teste[0]

3.0

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=17)
knn.fit(x_treino, y_treino)
labels = knn.predict(x_teste)
labels

array([1., 1., 1., 1., 1., 1., 3., 1., 1., 3., 3., 3., 1., 3., 1., 1., 3.,
       3., 3., 1., 3., 3., 3., 1., 1., 1., 3., 1., 1., 1., 1., 3., 3., 1.,
       3., 1., 1., 1., 1., 1., 1., 3., 1., 1., 3., 1., 1., 3., 1., 3., 1.,
       1., 3., 3., 1., 1., 3., 1., 1., 1., 1., 1., 3., 3., 1., 1., 3., 3.,
       1., 1., 3., 3., 3., 3., 3., 1., 1., 3., 1., 3., 3., 3., 3., 1., 3.,
       1., 1., 1., 3., 1., 1., 1., 3., 1., 1., 3., 3., 3., 3., 3., 1., 3.,
       3., 3., 1., 1., 1., 3., 3., 1., 3., 1., 3., 3., 1., 3., 1., 1., 1.,
       1., 3., 3., 1., 3., 3., 3., 3., 3., 1., 3., 1., 1., 1., 3., 1., 1.,
       1., 3., 1., 1., 1., 1., 3., 3., 1., 3., 3., 1., 3., 3., 3., 3., 3.,
       1., 1., 3., 1., 1., 3., 1., 1., 3., 3., 1., 1., 1., 3., 1., 3., 3.,
       1., 3., 3., 3., 1., 1., 1., 1., 3., 1., 3., 3., 1., 3., 3., 3., 3.,
       1.])

In [11]:
y_teste

array([3., 1., 1., 3., 1., 1., 3., 1., 1., 3., 3., 3., 1., 2., 1., 1., 3.,
       3., 3., 2., 3., 3., 3., 1., 1., 1., 3., 1., 1., 3., 1., 3., 3., 1.,
       3., 1., 1., 1., 1., 3., 2., 3., 3., 1., 3., 2., 2., 3., 2., 3., 1.,
       1., 3., 3., 1., 1., 3., 1., 1., 2., 1., 1., 3., 3., 1., 1., 3., 3.,
       1., 1., 3., 3., 3., 3., 3., 1., 1., 3., 1., 3., 3., 2., 3., 1., 3.,
       2., 1., 1., 3., 1., 1., 1., 3., 1., 1., 3., 3., 3., 3., 3., 1., 2.,
       3., 3., 1., 2., 1., 3., 3., 1., 3., 1., 3., 3., 1., 3., 1., 1., 1.,
       1., 3., 3., 1., 3., 3., 3., 3., 3., 2., 3., 1., 1., 2., 3., 1., 1.,
       1., 3., 1., 1., 1., 3., 3., 3., 1., 3., 3., 1., 3., 3., 3., 3., 3.,
       1., 3., 3., 2., 1., 2., 1., 1., 3., 3., 1., 1., 1., 3., 1., 3., 2.,
       1., 3., 3., 3., 2., 1., 1., 1., 3., 1., 3., 2., 1., 3., 3., 3., 3.,
       1.])

In [12]:
np.sum(labels == y_teste)

163

In [13]:
(labels == y_teste).sum()

163

In [14]:
#porcentual de acerto
100 * (labels == y_teste).sum()/len(x_teste)

86.70212765957447

In [15]:
knn.score(x_teste, y_teste)

0.8670212765957447

In [16]:
np.mean(labels==y_teste)

0.8670212765957447