In [1]:
import numpy as np

In [2]:
val1, val2, val3 = np.loadtxt('carregar_dados_de_arquivo-dados.txt',skiprows=1, unpack=True)
print(val1)
print(val2)
print(val3)

[0.1212 0.104  0.5661 0.762 ]
[0.842    0.5422   0.932    0.847361]
[0.3672  0.34551 0.2344  0.1538 ]


In [4]:
array = np.genfromtxt('carregar_dados_de_arquivo-dados2.txt',skip_header=1, filling_values=1000)
print(array)

[[1.21200e-01 8.42000e-01 3.67200e-01]
 [1.00000e+03 5.42200e-01 3.45510e-01]
 [5.66100e-01 9.32000e-01 1.00000e+03]
 [7.62000e-01 8.47361e-01 1.53800e-01]]
