In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
np.delete(a,1,axis=0)

array([[1, 2],
       [5, 6]])

In [4]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
np.delete(a,0,axis=1)

array([[2],
       [4],
       [6]])

In [6]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
np.delete(a, np.s_[::2],axis=0)

array([[ 4,  5,  6],
       [10, 11, 12]])

In [10]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])