In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [4]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [5]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [6]:
np.repeat(a,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [7]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [8]:
#CONTINUAÇÃO - REPETINDO ARRAY AO LONGO DE UM EIXO

In [10]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
np.tile(a,2)

array([1, 2, 3, 1, 2, 3])

In [12]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [13]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [14]:
np.tile(b,2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])